image: java:8-jdk

stages:
  - test
  - compileConsumer
  - compileProducer

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

test:
  stage: test
  script:
    - ./gradlew testAll
  only:
    - master

compileConsumer:
  stage: compileConsumer
  script:
    - ./gradlew packageConsumerJar
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 week
  only:
    - master

compileProducer:
  stage: compileProducer
  script:
    - ./gradlew packageProducerJar
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 week
  only:
    - master


after_script:
  - echo "End CI"