image: java:8-jdk

stages:
  - test
  - consumer
  - producer
  - kafka

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

test:
  stage: test
  script:
    - ./gradlew testAll

consumer:
  stage: consumer
  script:
    - ./gradlew packageConsumerJar
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 day

producer:
  stage: producer
  script:
    - ./gradlew packageProducerJar
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 day

kafka:
  stage: kafka
  script:
    - ./gradlew packageKafkaCommunicationJar
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 day

after_script:
  - echo "End CI"