image: java:8-jdk

stages:
  - test
  - consumer
  - producer

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

test:
  stage: test
  script:
    - ./gradlew testAll
  only:
    - master
    - recette

consumer:
  stage: consumer
  script:
    - ./gradlew packageConsumerJar
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 day
  only:
    - master
    - recette

producer:
  stage: producer
  script:
    - ./gradlew packageProducerJar
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 day
  only:
    - master
    - recette


after_script:
  - echo "End CI"